name: Build base images

on: 
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version for tagging and releasing"
        
env:
  BUILD_TYPE: base

jobs:
  build:
    name: Build armv7 base image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5.0.0

      - name: Check if requirements files changed
        id: requirements
        run: |
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            $BUILD_ARGS \
            --armv7 \
            --target /data \
            --cosign \
            --generic ${{ github.event.inputs.version }}
